Algoritmo "APS 1, Problema A"
// Disciplina   : Algoritmo
// Professor   : Andre Cotelli
Var
// Seção de Declarações das variáveis 
n1,n2,n3,n4,n5,n6,n7,n8,n9,n10,media : real;

Inicio
escreval("escreva 10 numeros: ")
leia(n1)
leia(n2)
leia(n3)
leia(n4)
leia(n5)
leia(n6)
leia(n7)
leia(n8)
leia(n9)
leia(n10)

media := (n1+n2+n3+n4+n5+n6+n7+n8+n9+n10)/10

escreval("Media desses numeros: ",media)

Fimalgoritmo